name: CI
on: ["push", "pull_request"]

jobs:
  test:
    name: "Contracts: Test contracts"
    runs-on: ubuntu-latest
    env:
      REPORT_GAS: true
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Install dependencies
        run: npm install --frozen-lockfile

      - name: Compile nft contracts
        run: npx hardhat compile

      - name: Test nft contracts
        run: npx hardhat test

  coverage:
    name: "Contracts: Coverage Report"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v2
        with:
          node-version: 16
      - uses: actions/cache@v2
        id: cache
        with:
          path: "**/node_modules"
          key: npm-v2-${{ hashFiles('**/package-lock.json') }}
          restore-keys: npm-v2-

      - name: Install packages
        run: npm ci
        if: steps.cache.outputs.cache-hit != 'true'

      - name: Coverage of contracts
        run: npx hardhat coverage
        env:
          NODE_OPTIONS: --max_old_space_size=4096
      - name: Codecov
        uses: codecov/codecov-action@v2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
